[package]
name = "adventofcode_2023day_05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = {path = "../../utils"}
test-case = "*"
rangemap = "1.4.0"
